// export const RECIPIENT_MAPPING = {
//   dg: "The Director General",
//   ps: "The Permanent Secretary",
//   es: "The Executive Secretary",
//   gm: "The General Manager",
//   cmd: "The Chief Medical Director",
//   ceo: "The Chief Executive Officer",
//   pmg: "The Post Master General",
//   ed: "The Executive Director",
//   hos: "The Head of Service",
//   hm: "The Honourable Minister",
//   reg: "The Registrar",
// };
export const RECIPIENTS = [
  "The Director General",
  "The Permanent Secretary",
  "The Executive Secretary",
  "The General Manager",
  "The Chief Medical Director",
  "The Chief Executive Officer",
  "The Post Master General",
  "The Executive Director",
  "The Head of Service",
  "The Honourable Minister",
  "The Registrar",
];
